### ISSUE TITLE
部署的时候提示缺少 manifest.yml

### ISSUE THREAD

**Issue by huacnlee** [luikore/nyara#34]
``` bash
/home/huacnlee/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/psych.rb:299:in `initialize': No such file or directory - /home/huacnlee/www/iPress/public/manifest.yml (Errno::ENOENT)
    from /home/huacnlee/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/psych.rb:299:in `open'
    from /home/huacnlee/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/psych.rb:299:in `load_file'
    from /home/huacnlee/www/iPress/config/production.rb:10:in `block in <top (required)>'
    from /home/huacnlee/.rvm/gems/ruby-2.0.0-p247/bundler/gems/nyara-86ddc80c7203/lib/nyara/config.rb:184:in `instance_eval'
    from /home/huacnlee/.rvm/gems/ruby-2.0.0-p247/bundler/gems/nyara-86ddc80c7203/lib/nyara/config.rb:184:in `configure'
    from /home/huacnlee/.rvm/gems/ruby-2.0.0-p247/bundler/gems/nyara-86ddc80c7203/lib/nyara/config.rb:194:in `configure'
    from /home/huacnlee/www/iPress/config/production.rb:2:in `<top (required)>'
    from /home/huacnlee/www/iPress/config/application.rb:28:in `require_relative'
```

**Comment by luikore** [comment]
要先

``` sh
rake assets:build
```

参见 https://github.com/luikore/nyara/wiki/Deploy#assets

**Comment by huacnlee** [comment]
`rake assets:build` 不会产生 `manifest.yml` 的

**Comment by SaitoWu** [comment]
https://github.com/huacnlee/iPress/pull/1 解决了问题, 并且优化了一下之前的 js 与 css 配置.
