### ISSUE TITLE
nyara server -e production -p 4001 -d 出错

### ISSUE THREAD

**Issue by huacnlee** [luikore/nyara#35]
``` bash
$ nyara server -e production -p 4001 -d
/home/huacnlee/.rvm/gems/ruby-2.0.0-p247/bundler/gems/nyara-86ddc80c7203/lib/nyara/command.rb:118:in `server': undefined method `shellescape' for 4001:Fixnum (NoMethodError)
    from /home/huacnlee/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /home/huacnlee/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /home/huacnlee/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /home/huacnlee/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /home/huacnlee/.rvm/gems/ruby-2.0.0-p247/bundler/gems/nyara-86ddc80c7203/bin/nyara:5:in `<top (required)>'
    from /home/huacnlee/.rvm/gems/ruby-2.0.0-p247/bin/nyara:23:in `load'
    from /home/huacnlee/.rvm/gems/ruby-2.0.0-p247/bin/nyara:23:in `<main>'
    from /home/huacnlee/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
    from /home/huacnlee/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by luikore** [comment]
还有些可以改进的地方:
- [ ] 保存 pid
- [ ] 改成用 `GetoptLong` 解析参数
